env:
  browser: true
  es2021: true
  react-native/react-native: true
settings:
  react:
    version: 'detect'
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'prettier'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
  - react-native
  - unused-imports
rules:
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  '@typescript-eslint/no-unused-vars':
    - error
  unused-imports/no-unused-imports:
    - error
  'react/display-name':
    - off
  '@typescript-eslint/no-empty-function':
    - off
overrides:
  - files: ['**/*.tsx']
    rules:
      'react/prop-types':
        - off
